# Generated by Django 4.1.1 on 2022-11-15 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('admin', 'Admin')], default='developer', max_length=255),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=250)),
                ('expired_at', models.DateField()),
                ('priority', models.IntegerField()),
                ('state', models.CharField(choices=[('new_task', 'New'), ('in_development', 'In Development'), ('in_qa', 'In Qa'), ('in_code_review', 'In Code Review'), ('ready_for_release', 'Ready For Release'), ('released', 'Released'), ('archived', 'Archived')], default='new_task', max_length=20)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_user_assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_user_author', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tag')),
            ],
        ),
    ]
